= Support scenarios in deployments

xtUML Project Design Note

== 1 Abstract

This note describes the design chosen to implement sequenced scenario creation. 

== 2 Introduction and Background

See <<dr-2, Analysis Introduction and Background>>.

== 3 Requirements

See <<dr-2, Analysis Requirements>>.

== 4 Analysis

See <<dr-2, Analysis>>.


== 5 Design
=== 5.1 Function import into deployment

==== 5.1.1 Terminator sequences
To minimize the impact on existing deployment logic these new elements are added to the Deployment subsystem.

. Terminator Service Sequence (O_OBJ)
. Service In Sequence (O_OBJ)
. R1658 (1 Terminator - 1 Terminator Service Sequence)
. R1659 (1 Terminator Service Sequence - * Service In Sequence)
. R1660 (1 Terminator Service - 0..1 Service In Sequence)
. RR1661 (0..1 Service In Sequence - 0..1 Service In Sequnce)

These two classes together capture ordering of terminators under a sequenced terminator.

==== 5.1.2 Scenario chooser dialog

==== 5.1.2.1 Menu Entry
A new CME function is created, D_DEPL_ImportScenariosFromComponent.  This function is currently marked as translate native.  The infrastructure will not be updated at this time to provide the necessary support required for initial ordering.

Two new entries are added to context_menu.pei.sql, one for the menu entry itself and one for a filter.

The filter is required as the design shall only allow one sequence terminator per deployment.  The filter is supported by an added actionFilter operation in the D_DEPL class.  This action filter prevents the menu entry from showin if:

. There is already a sequenced terminator under the selected deployment.
. There are no packages named "scenarios" within the workspace. 

==== 5.1.2.2 Order maintainence in dialog
The ElementSelectionDialog and ElementSelectionFlatView classes are extended to support maintaining selection order.  This is done by adding a separate list containing the elements in an insertion order.  The elements present in this list are displayed in a new text area above the element chooser list.  This allows the user to see the current ordered selection.  Any clients of these changes will have the ordered list returned by getSelection() if they specify ordered selection.

==== 5.1.3 Import function and supporting operations
The D_DEPL_ImportScenariosFromComponent wizard is designed to create the new sequenced terminator, then create a terminator service for each function returned from the element selection dialog.

This functionality is supported by two new operations:

. D_DEPL.createTerminatorForScenarios()
. D_TERM.importFunctionAsTerminator(func: inst_ref<Function_c>)

D_DEPL.createTerminatorForScenarios() creates a new terminator under the selected deployment with the following conditions:

- Domain_Name = Deployment.Name
- Terminator_Name = Sequence

D_TERM.importFunctionAsTerminator() creates a new terminator service with the appropriate data copied over from the function.  Additionally, a new Terminator Service Sequence is created if not present already.  Then each call correctly sets up the ordering through the R1661.

=== 5.1.2 Move Up/Down
New move up/down entries are added to the context_menu.pei.sql data.  Each one also has a filter added with a corresponding actionFilter operation added to D_TSVC.  The action filter hides the up or down if at the beginning or the end of the list.

A new function is added to the Terminator Service class, changeOrder(destination: integer).  The operation calls onto a matching operation in the Service In Sequence class.  For the move up and down function the destination is the current index +/- 1.  

The logic to support move up and down is designed to take a destination and adjust ordering according to that.  Designing the logic in this way will allow for supporting drag and drop, or any method which simply passes the desired array destination.

=== 5.1.3 Import and Export
The file_io.pei.sql and stream.pei.sql files are updated to persist the two new classes through the new associations.

== 6 Design Comments

During development <<dr-3,MC-Java issues with referentials under the consistency check logic>> was seen.  This work manually addressed the issue by hand editting the model files.  However, the issue was easy enough to fix during this work.  The change was made in its own PR but is documented here.

During formalization of an association a new base attribute is created an then converted to a referential attribute.  Part of this conversion process is to set the attribute type to same as base.  The O_RATTR.setDatatype() operation is used for this purpose.  This operation was designed to exclude cases where a base attribute was not associated across R113, likely during paste.  On the creation side we were calling setDatatype() before associating across R113.  In O_ATTR.migrateBaseToReferential() the call to setDatatype() is removed.  In both O_OBJ.newReferentialAttribute() and O_ATTR.combine_refs() a call to setDatatype() is added.

== 7 User Documentation


== 8 Unit Test
. [[Setup]]Setup
- Create a new project (Domain1)
- Create a new component (Domain1)
- Create a new package (scenarios)
- Add three functions: (1, 2, 3)
- Create a new project (Domain2)
- Create a new component (Domain2)
- Create a new package (scenarios)
- Add three functions: (1, 2, 3)
- Create a new project (Deployment)
- Create a new deployment (Domain12)
. Scenario import, and initial ordering
- Right click Domain Deployment
* Import scenarios from component is present
- Click Import scenarios from component
* Chooser Dialog is shown
* Chooser Dialog lists functions from Domain1 and Domain2
- Holding add to selection modifier (command in OSX) Select in order: Domain1::1, Domain2::2, Domain1::3
* The order selected is shown in the top "Selected:" field
- Click OK
* The Deployment as a new Terminator added (Domain12::Sequence)
* The Terminator has the selected functions imported as services in the same order as selected in the dialog
- Double click a service
* The OAL from the function has been copied over
. Move up/Move Down
- Select the middle terminator service
- Right click
* The Move Up and Move Down menu items are present
- Right click the first terminator service
* The Move Up menu item is not present
* The Move Down menu item is present
- Right click the last terminator service
* The Move Up menu item is present
* The Move Down menu item is not present
- Right click the middle terminator service and select Move Up
* The terminator service is moved up by one
- Right click the middle terminator service and select Move Down
* The terminator service is moved down by one
- Right click the first terminator service and select Move Down
* The terminator service is moved down by one
- Right click the last terminator service and select Move Up
* The terminator service is moved up by one
. Import scenarios menu item
- In a workspace that contains a deployment, but no (scenarios) pacakges right click the deployment
* The Import scenarios from component menu item is not present
- In a workspace with the same configuration created in <<Setup, Setup>>, right click the deployment after importing scenarios.
* The Import scenarios from component menu item is not present

== 9 Document References

In this section, list all the documents that the reader may need to refer to.
Give the full path to reference a file.

. [[dr-1]] https://support.onefact.net/issues/11455[11455 - export deployment (build set)]
. [[dr-2]] https://github.com/travislondon/bridgepoint/blob/master/doc-bridgepoint/notes/11455_deployments/11455_deployments_scenarios.ant.adoc
. [[dr-3]] https://support.onefact.net/issues/9573[9573 - MC-Java issues with referentials under the consistency check logic]

---

This work is licensed under the Creative Commons CC0 License

---
